### ISSUE TITLE
The librehealth logo in SVG

### ISSUE THREAD

**Issue by sunbiz** [LibreHealthIO/community-design-assets#1]
The logo should be available in SVG, since it is vector-based, easy to interchange to multiple formats, replicable and web-enabled asset.

**Comment by downeym** [comment]
Will to render both orange & white over transparent, with wordmark. Any other SVG styles needed for this?

**Comment by sunbiz** [comment]
I guess we could change the rendered colors using JavaScript, so either with transparent background will work. The shape looks fairly geometric to me. So will be nice if its creatable with shapes and not paths.

**Comment by downeym** [comment]
@sunbiz  Let me know if these look good to you.
